apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2022-05-14T05:03:22Z"
  labels:
    app: test-sliit
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:labels:
          .: {}
          f:app: {}
      f:spec:
        f:ports:
          .: {}
          k:{"port":3000,"protocol":"TCP"}:
            .: {}
            f:port: {}
            f:protocol: {}
            f:targetPort: {}
        f:selector:
          .: {}
          f:app: {}
        f:sessionAffinity: {}
        f:type: {}
    manager: kubectl
    operation: Update
    time: "2022-05-14T05:03:21Z"
  name: test-sliit
  namespace: default
  resourceVersion: "9756"
  selfLink: /api/v1/namespaces/default/services/test-sliit
  uid: 5866299b-fe19-42b4-b23c-f5e5d1cdba91
spec:
  clusterIP: 10.97.154.58
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: test-sliit
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}

